# Generated by Django 4.1 on 2025-03-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenFlockToInfo',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='UUID')),
                ('user_id', models.CharField(max_length=32, verbose_name='用户ID')),
                ('farmName', models.CharField(max_length=32, verbose_name='农场名称')),
                ('batch_name', models.CharField(max_length=255, verbose_name='批次名称')),
                ('incubation_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='孵化日期')),
                ('chicken_seedling_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='鸡苗数量')),
                ('vaccine_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='疫苗ID')),
                ('vaccine_manufacturers', models.CharField(blank=True, max_length=255, null=True, verbose_name='疫苗供应商')),
                ('d1', models.CharField(blank=True, max_length=255, null=True, verbose_name='d1')),
                ('d2', models.CharField(blank=True, max_length=255, null=True, verbose_name='d2')),
                ('d3', models.CharField(blank=True, max_length=255, null=True, verbose_name='d3')),
                ('data_version', models.IntegerField(verbose_name='数据版本')),
                ('status', models.CharField(max_length=2, verbose_name='状态[0:已关闭,1:活动中]')),
                ('create_time', models.CharField(max_length=50, verbose_name='新增时间')),
                ('create_by', models.CharField(max_length=32, verbose_name='新增人')),
                ('update_time', models.CharField(max_length=50, verbose_name='更新时间')),
                ('update_by', models.CharField(max_length=32, verbose_name='更新人')),
                ('deleted', models.BooleanField(default=0, max_length=32, verbose_name='数据是否已删除[0:未删除,1:已删除]')),
            ],
        ),
        migrations.CreateModel(
            name='ChickenFlockInfo',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='UUID')),
                ('user_id', models.CharField(max_length=32, verbose_name='用户ID')),
                ('batch_name', models.CharField(max_length=255, verbose_name='批次名称')),
                ('incubation_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='孵化日期')),
                ('chicken_seedling_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='鸡苗数量')),
                ('vaccine_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='疫苗ID')),
                ('vaccine_manufacturers', models.CharField(blank=True, max_length=255, null=True, verbose_name='疫苗供应商')),
                ('d1', models.CharField(blank=True, max_length=255, null=True, verbose_name='d1')),
                ('d2', models.CharField(blank=True, max_length=255, null=True, verbose_name='d2')),
                ('d3', models.CharField(blank=True, max_length=255, null=True, verbose_name='d3')),
                ('data_version', models.IntegerField(verbose_name='数据版本')),
                ('status', models.CharField(max_length=2, verbose_name='状态[0:已关闭,1:活动中]')),
                ('create_time', models.CharField(max_length=50, verbose_name='新增时间')),
                ('create_by', models.CharField(max_length=32, verbose_name='新增人')),
                ('update_time', models.CharField(max_length=50, verbose_name='更新时间')),
                ('update_by', models.CharField(max_length=32, verbose_name='更新人')),
                ('deleted', models.BooleanField(default=0, max_length=32, verbose_name='数据是否已删除[0:未删除,1:已删除]')),
            ],
            options={
                'db_table': 'chicken_flock_info',
                'unique_together': {('id', 'data_version')},
            },
        ),
    ]
