# Generated by Django 4.1 on 2025-03-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmOtherAttributesInfo',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='UUID')),
                ('user_id', models.CharField(max_length=32, verbose_name='用户ID')),
                ('farm_id', models.CharField(max_length=32, verbose_name='农场ID')),
                ('sensitive', models.CharField(max_length=5000, verbose_name='敏感性')),
                ('intermediate', models.CharField(max_length=255, verbose_name='中间性')),
                ('resistant', models.CharField(max_length=255, verbose_name='抵抗性')),
                ('antibiotic', models.CharField(max_length=255, verbose_name='抗生素')),
                ('bacterial_type', models.CharField(max_length=255, verbose_name='菌类')),
                ('data_time', models.CharField(max_length=10, verbose_name='数据时间')),
                ('data_version', models.IntegerField(verbose_name='数据版本')),
                ('create_time', models.CharField(max_length=50, verbose_name='新增时间')),
                ('create_by', models.CharField(max_length=32, verbose_name='新增人')),
                ('update_time', models.CharField(max_length=50, verbose_name='更新时间')),
                ('update_by', models.CharField(max_length=32, verbose_name='更新人')),
                ('deleted', models.BooleanField(default=0, max_length=32, verbose_name='数据是否已删除[0:未删除,1:已删除]')),
            ],
            options={
                'db_table': 'farm_other_attributes_info',
                'unique_together': {('id', 'data_time', 'data_version')},
            },
        ),
    ]
