# Generated by Django 4.1 on 2025-03-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcesInfo',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='资源名称')),
                ('path', models.TextField(verbose_name='资源存放路径')),
                ('resources_type', models.CharField(max_length=2, verbose_name='资源类型[0:消息附件],1:表格附件')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='文件类型')),
                ('person', models.CharField(max_length=32, verbose_name='所属管理员ID')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.CharField(max_length=50, verbose_name='新增时间')),
                ('create_by', models.CharField(max_length=32, verbose_name='新增人')),
                ('update_time', models.CharField(max_length=50, verbose_name='更新时间')),
                ('update_by', models.CharField(max_length=32, verbose_name='更新人')),
                ('deleted', models.BooleanField(default=0, max_length=32, verbose_name='数据是否已删除[0:未删除,1:已删除]')),
            ],
            options={
                'db_table': 'resources_info',
            },
        ),
    ]
