# Generated by Django 4.1 on 2024-03-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DictInfo",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                ("user_id", models.CharField(max_length=32, verbose_name="用户ID")),
                ("dict_type", models.CharField(max_length=32, verbose_name="养殖额度")),
                (
                    "chinese_name",
                    models.TextField(max_length=10000, verbose_name="中文名称"),
                ),
                ("english_name", models.CharField(max_length=100, verbose_name="英文名称")),
                ("create_time", models.CharField(max_length=50, verbose_name="新增时间")),
                ("create_by", models.CharField(max_length=32, verbose_name="新增人")),
                ("update_time", models.CharField(max_length=50, verbose_name="更新时间")),
                ("update_by", models.CharField(max_length=32, verbose_name="更新人")),
                (
                    "deleted",
                    models.BooleanField(
                        default=0, max_length=32, verbose_name="数据是否已删除[0:未删除,1:已删除]"
                    ),
                ),
            ],
            options={
                "db_table": "dict_info",
                "unique_together": {("id",)},
            },
        ),
    ]
