# Generated by Django 4.1 on 2025-03-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictinfo',
            name='dict_type',
            field=models.CharField(max_length=32, verbose_name='类型'),
        ),
    ]
